// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKR7RPbjagzczHwhD6kgspIqSSj8D7a4',
    appId: '1:767971588081:web:d55980ff836943702e3650',
    messagingSenderId: '767971588081',
    projectId: 'message-app-sara',
    authDomain: 'message-app-sara.firebaseapp.com',
    storageBucket: 'message-app-sara.firebasestorage.app',
    measurementId: 'G-4SPEXHH14C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4gjPbtfzLbNX879Qg4BOx6NWFfA6wnw',
    appId: '1:767971588081:android:bc13d45e862ccf932e3650',
    messagingSenderId: '767971588081',
    projectId: 'message-app-sara',
    storageBucket: 'message-app-sara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQprSnO-OLSkRSzSgQcjewwqT3xCVZn3w',
    appId: '1:767971588081:ios:c8edd86244f399392e3650',
    messagingSenderId: '767971588081',
    projectId: 'message-app-sara',
    storageBucket: 'message-app-sara.firebasestorage.app',
    iosBundleId: 'com.example.messagePostFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQprSnO-OLSkRSzSgQcjewwqT3xCVZn3w',
    appId: '1:767971588081:ios:c8edd86244f399392e3650',
    messagingSenderId: '767971588081',
    projectId: 'message-app-sara',
    storageBucket: 'message-app-sara.firebasestorage.app',
    iosBundleId: 'com.example.messagePostFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADKR7RPbjagzczHwhD6kgspIqSSj8D7a4',
    appId: '1:767971588081:web:9e14473ddbec557e2e3650',
    messagingSenderId: '767971588081',
    projectId: 'message-app-sara',
    authDomain: 'message-app-sara.firebaseapp.com',
    storageBucket: 'message-app-sara.firebasestorage.app',
    measurementId: 'G-C1VDFM7L17',
  );
}
